stages:
  - build

#build:windows:
#  stage: build
#  only:
#    - master
#  tags:
#    - windows
#  before_script:
#    - git submodule update --init --recursive
#    - choco install -y cmake
#    - choco install -y python
#    - $env:Path += ';C:\Program Files\CMake\bin'
#  script:
#    - mkdir build
#    - cd build
#    - cmake -G "Visual Studio 16 2019" ..
#    - cmake --build . --target ALL_BUILD --config Release

build:linux:gcc:
  stage: build
  only:
    - master
  image: registry.gitlab.com/digital-vessel/docker/build_environment/linux:latest
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -G "Unix Makefiles" ..
    - cmake --build .

build:linux:clang:
  stage: build
  only:
    - master
  image: registry.gitlab.com/digital-vessel/docker/build_environment/linux:latest
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -G "Unix Makefiles" ..
    - cmake --build .
