stages:
  - build
  - test

build:windows:
  stage: build
  tags:
    - windows-1809
  before_script:
    - git submodule update --init --recursive
    - choco install -y cmake.install --installargs '"ADD_CMAKE_TO_PATH=System"'
    - choco install -y python
    - choco upgrade -y visualstudio2019buildtools
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -G "Visual Studio 16 2019" ..
    - cmake --build . --target ALL_BUILD --config Release
  artifacts:
    paths:
      - build/

build:linux:gcc:
  stage: build
  image: registry.gitlab.com/digital-vessel/garlic-engine/garlic/build_environment/linux:20.04
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -G "Unix Makefiles" ..
    - cmake --build .
  artifacts:
    paths:
      - build/

build:linux:clang:
  stage: build
  image: registry.gitlab.com/digital-vessel/garlic-engine/garlic/build_environment/linux:20.04
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/clang-10 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-10 -G "Unix Makefiles" ..
    - cmake --build .
  artifacts:
    paths:
      - build/

test:windows:
  stage: test
  tags:
    - windows-1809
  before_script:
    - choco install -y cmake.install --installargs '"ADD_CMAKE_TO_PATH=System"'
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build:windows
  needs:
    - build:windows

test:linux:gcc:
  stage: test
  image: registry.gitlab.com/digital-vessel/garlic-engine/garlic/build_environment/linux:20.04
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build:linux:gcc
  needs:
    - build:linux:gcc

test:linux:clang:
  stage: test
  image: registry.gitlab.com/digital-vessel/garlic-engine/garlic/build_environment/linux:20.04
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build:linux:clang
  needs:
    - build:linux:clang