#Variables / Anchors
.windows_prepare: &set_up_windows_env
  before_script:
    - git submodule update --init --recursive
    - choco install -y cmake
    - choco install -y python
    - choco upgrade -y visualstudio2019buildtools
    - curl.exe -o vksdk.exe https://sdk.lunarg.com/sdk/download/1.2.154.1/windows/VulkanSDK-1.2.154.1-Installer.exe?Human=true
    - .\vksdk.exe /S /D=C:\VulkanSDK | Out-Null
    - $env:VULKAN_SDK = 'C:\VulkanSDK'
    - $env:Path += ';C:\Program Files\CMake\bin;C:\VulkanSDK\Bin'

variables:
  LINUX_ENV_IMAGE: registry.gitlab.com/digital-vessel/garlic-engine/garlic/build_environment/linux:3.0.0

stages:
  - build-engine
  - test-engine
  - build-editor

#Build: Engine
build-engine-release-msvc:
  stage: build-engine
  tags:
    - windows-1809
  <<: *set_up_windows_env
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -G "Visual Studio 16 2019" ..
    - cmake --build . --target ALL_BUILD --config Release
  artifacts:
    paths:
      - build/

build-engine-debug-msvc:
  stage: build-engine
  tags:
    - windows-1809
  <<: *set_up_windows_env
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_ENABLE_DEBUG_DEFINITION=ON -G "Visual Studio 16 2019" ..
    - cmake --build . --target ALL_BUILD --config Debug

build-engine-release-gcc:
  stage: build-engine
  image: &LINUX_ENV_IMAGE
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -G "Unix Makefiles" ..
    - cmake --build .
  artifacts:
    paths:
      - build/

build-engine-debug-gcc:
  stage: build-engine
  image: &LINUX_ENV_IMAGE
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_ENABLE_DEBUG_DEFINITION=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -G "Unix Makefiles" ..
    - cmake --build .

build-engine-release-clang:
  stage: build-engine
  image: &LINUX_ENV_IMAGE
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 -G "Unix Makefiles" ..
    - cmake --build .
  artifacts:
    paths:
      - build/

build-engine-debug-clang:
  stage: build-engine
  image: &LINUX_ENV_IMAGE
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_ENABLE_DEBUG_DEFINITION=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 -G "Unix Makefiles" ..
    - cmake --build .

#Test: Engine
test-engine-msvc:
  stage: test-engine
  tags:
    - windows-1809
  before_script:
    - choco install -y cmake
    - $env:Path += ';C:\Program Files\CMake\bin'
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build-engine-release-msvc
  needs:
    - build-engine-release-msvc

test-engine-gcc:
  stage: test-engine
  image: &LINUX_ENV_IMAGE
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build-engine-release-gcc
  needs:
    - build-engine-release-gcc

test-engine-clang:
  stage: test-engine
  image: &LINUX_ENV_IMAGE
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build-engine-release-clang
  needs:
    - build-engine-release-clang

#Build: Editor
build-editor-release-msvc:
  stage: build-editor
  tags:
    - windows-1809
  <<: *set_up_windows_env
  script:
    - cd Scape/Editor
    - dotnet build -c Release
  dependencies:
    - build-engine-release-msvc

build-editor-debug-msvc:
  stage: build-editor
  tags:
    - windows-1809
  <<: *set_up_windows_env
  script:
    - cd Scape/Editor
    - dotnet build -c Debug
  dependencies:
    - build-engine-release-msvc

build-editor-release-gcc:
  stage: build-editor
  image: &LINUX_ENV_IMAGE
  before_script:
    - git submodule update --init --recursive
  script:
    - cd Scape/Editor
    - dotnet build -c Release
  dependencies:
    - build-engine-release-gcc

build-editor-debug-gcc:
  stage: build-editor
  image: &LINUX_ENV_IMAGE
  before_script:
    - git submodule update --init --recursive
  script:
    - cd Scape/Editor
    - dotnet build -c Debug
  dependencies:
    - build-engine-release-gcc