stages:
  - build

build:windows:
  stage: build
  tags:
    - windows
  before_script:
    - choco install -y cmake
    - $env:Path += ';C:\Program Files\CMake\bin'
  script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 16 2019" ..
    - cmake --build .