stages:
  - build-engine
  - build-editor
  - test-engine

build:engine:msvc:
  stage: build-engine
  tags:
    - windows-1809
  before_script:
    - git submodule update --init --recursive
    - choco install -y cmake
    - choco install -y python
    - choco upgrade -y visualstudio2019buildtools
    - curl.exe -o vksdk.exe https://sdk.lunarg.com/sdk/download/1.2.154.1/windows/VulkanSDK-1.2.154.1-Installer.exe?Human=true
    - .\vksdk.exe /S /D=C:\VulkanSDK | Out-Null
    - $env:VULKAN_SDK = 'C:\VulkanSDK'
    - $env:Path += ';C:\Program Files\CMake\bin'
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -G "Visual Studio 16 2019" ..
    - cmake --build . --target ALL_BUILD --config Release
  artifacts:
    paths:
      - build/

build:engine:gcc:
  stage: build-engine
  image: registry.gitlab.com/digital-vessel/garlic-engine/garlic/build_environment/linux:3.0.0
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -G "Unix Makefiles" ..
    - cmake --build .
  artifacts:
    paths:
      - build/

build:engine:clang:
  stage: build-engine
  image: registry.gitlab.com/digital-vessel/garlic-engine/garlic/build_environment/linux:3.0.0
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 -G "Unix Makefiles" ..
    - cmake --build .
  artifacts:
    paths:
      - build/

build:editor:msvc:
  stage: build-editor
  tags:
    - windows-1809
  before_script:
    - git submodule update --init --recursive
    - choco install -y cmake
    - choco install -y python
    - choco upgrade -y visualstudio2019buildtools
    - $env:Path += ';C:\Program Files\CMake\bin'
  script:
    - cd Scape/Editor
    - dotnet build -c Release
  dependencies:
    - build:engine:msvc

build:editor:gcc:
  stage: build-editor
  image: registry.gitlab.com/digital-vessel/garlic-engine/garlic/build_environment/linux:3.0.0
  before_script:
    - git submodule update --init --recursive
  script:
    - cd Scape/Editor
    - dotnet build -c Release
  dependencies:
    - build:engine:gcc

test:engine:msvc:
  stage: test-engine
  tags:
    - windows-1809
  before_script:
    - choco install -y cmake
    - $env:Path += ';C:\Program Files\CMake\bin'
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build:engine:msvc

test:engine:gcc:
  stage: test-engine
  image: registry.gitlab.com/digital-vessel/garlic-engine/garlic/build_environment/linux:3.0.0
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build:engine:gcc

test:engine:clang:
  stage: test-engine
  image: registry.gitlab.com/digital-vessel/garlic-engine/garlic/build_environment/linux:3.0.0
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build:engine:clang