#Variables / Anchors
.windows_prepare: &set_up_windows_env
  before_script:
    - git submodule update --init --recursive
    - choco install -y cmake
    - choco install -y python
    - choco upgrade -y visualstudio2019buildtools
    - curl.exe -o vksdk.exe https://sdk.lunarg.com/sdk/download/1.2.154.1/windows/VulkanSDK-1.2.154.1-Installer.exe?Human=true
    - .\vksdk.exe /S /D=C:\VulkanSDK | Out-Null
    - $env:VULKAN_SDK = 'C:\VulkanSDK'
    - $env:Path += ';C:\Program Files\CMake\bin;C:\VulkanSDK\Bin'

.windows_tag: &windows_runner_tags
  tags:
    - windows-1809

.linux_image: &linux_env_image
  image: registry.gitlab.com/digital-vessel/garlic/garlic/build_environment/linux:3.0.0

stages:
  - build
  - test

#Build
build-release-msvc:
  stage: build
  <<: *windows_runner_tags
  <<: *set_up_windows_env
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -G "Visual Studio 16 2019" ..
    - cmake --build . --target ALL_BUILD --config Release
  artifacts:
    paths:
      - build/

build-debug-msvc:
  stage: build
  <<: *windows_runner_tags
  <<: *set_up_windows_env
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_ENABLE_DEBUG_DEFINITION=ON -G "Visual Studio 16 2019" ..
    - cmake --build . --target ALL_BUILD --config Debug
  artifacts:
    paths:
      - build/

build-release-gcc:
  stage: build
  <<: *linux_env_image
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -G "Unix Makefiles" ..
    - cmake --build .
  artifacts:
    paths:
      - build/

build-debug-gcc:
  stage: build
  <<: *linux_env_image
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_ENABLE_DEBUG_DEFINITION=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 -G "Unix Makefiles" ..
    - cmake --build .
  artifacts:
    paths:
      - build/

build-release-clang:
  stage: build
  <<: *linux_env_image
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 -G "Unix Makefiles" ..
    - cmake --build .
  artifacts:
    paths:
      - build/

build-debug-clang:
  stage: build
  <<: *linux_env_image
  before_script:
    - git submodule update --init --recursive
  script:
    - mkdir build
    - cd build
    - cmake -DGAR_ENABLE_DEBUG_DEFINITION=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-10 -DCMAKE_CXX_COMPILER=clang++-10 -G "Unix Makefiles" ..
    - cmake --build .
  artifacts:
    paths:
      - build/

#Test
test-msvc:
  stage: test
  <<: *windows_runner_tags
  before_script:
    - choco install -y cmake
    - $env:Path += ';C:\Program Files\CMake\bin'
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build-release-msvc
  needs:
    - build-release-msvc

test-gcc:
  stage: test
  <<: *linux_env_image
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build-release-gcc
  needs:
    - build-release-gcc

test-clang:
  stage: test
  <<: *linux_env_image
  script:
    - cd build
    - ctest -C Release
  dependencies:
    - build-release-clang
  needs:
    - build-release-clang