name: Static Analysis
on:
  pull_request:
    branches: [master]
jobs:
  cpp_check:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/agarlicmonkey/garlic/linux_analysis:1.0
      credentials:
        username: ${{ secrets.DOCKER_LOGIN_USERNAME }}
        password: ${{ secrets.DOCKER_LOGIN_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      #Suppress syntax errors as these are causing false positives
      - run: cppcheck -iclove/components/core/graphics/external/shaderc -iclove/external/stb ./ --suppress=syntaxError --error-exitcode=1
